#!/usr/bin/env python
"""
This script was generated as part of a driver_script file by the
setup_testcases.py script.
"""
import sys
import os
import shutil
import glob
import subprocess
import argparse


# This script was generated by setup_testcases.py as part of a driver_script
# file.
os.environ['PYTHONUNBUFFERED'] = '1'
parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument("--no_RMSE", dest="no_RMSE",
                    help="If set, RMSE case will not be run during "
                         "execution of this script.",
                    action="store_true")
parser.add_argument("--finalize_RMSE", dest="finalize_RMSE",
                    help="If set, RMSE case will have symlinks replaced "
                         "with the files they point to, this occurs after any "
                         "case runs that have been requested.",
                    action="store_true")

args = parser.parse_args()
base_path = os.getcwd()
dev_null = open('/dev/null', 'w')
error = False

if not args.no_RMSE:
    os.chdir(base_path)
    os.chdir('RMSE')

    print(" * Computing RMSE and convergence order...")
    # Run command is:
    # ./run.py
    subprocess.check_call(['./run.py'], stdout=dev_null, stderr=None)
    print("     complete!  Created file:  rmse/convergence.png")
if error:
    sys.exit(1)
if args.finalize_RMSE:
    old_dir = os.getcwd()
    os.chdir("RMSE")
    file_list = glob.glob("*")
    for file in file_list:
        if os.path.islink(file):
            link_path = os.readlink(file)
            os.unlink(file)
            shutil.copyfile(link_path, file)
    os.chdir(old_dir)

sys.exit(0)
